-- ============================================================
-- 024_order_idempotency
--
-- Adds an idempotency table for order creation so a retried POST
-- /api/orders (network hiccup, mobile back-button, double-tap)
-- returns the original order instead of creating a duplicate one.
--
-- Without this, a customer charged once via the payment gateway
-- can end up with 2 orders in the DB if the client retries — and
-- there's no way to reconcile from the server side because the
-- two POSTs look identical.
--
-- The contract:
--   • Client sends `Idempotency-Key: <uuid>` header (optional).
--   • Server uses (user_id, key) as a unique constraint.
--   • Second POST with the same key returns the existing order.
--   • Keys are per-user (a key generated by user A doesn't collide
--     with user B's key).
--
-- TTL: keys older than 24h are cleaned up by a sweep RPC. Inside
-- that window we treat the same key as the same order. Outside
-- the window the key is recycled (acceptable — clients don't keep
-- generated UUIDs that long).
-- ============================================================

CREATE TABLE IF NOT EXISTS public.order_idempotency_keys (
  user_id     UUID         NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  key         TEXT         NOT NULL CHECK (char_length(key) BETWEEN 8 AND 128),
  order_id    UUID         NOT NULL REFERENCES public.orders(id)   ON DELETE CASCADE,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, key)
);

-- Cleanup sweep — the cron route can call this.
CREATE INDEX IF NOT EXISTS order_idempotency_keys_created_at_idx
  ON public.order_idempotency_keys (created_at);

COMMENT ON TABLE public.order_idempotency_keys IS
  'Tracks (user_id, Idempotency-Key) → order_id mappings so retries return the original order. 24h TTL via cleanup_expired_idempotency_keys().';

-- ── RLS ───────────────────────────────────────────────────────
-- Service-role only — the API route runs server-side and never
-- exposes this table to clients.
ALTER TABLE public.order_idempotency_keys ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.order_idempotency_keys FROM authenticated, anon;
GRANT  ALL ON public.order_idempotency_keys TO service_role;

-- ── Cleanup sweep ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.cleanup_expired_idempotency_keys()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  deleted INT;
BEGIN
  DELETE FROM public.order_idempotency_keys
   WHERE created_at < now() - INTERVAL '24 hours';
  GET DIAGNOSTICS deleted = ROW_COUNT;
  RETURN deleted;
END;
$$;

GRANT EXECUTE ON FUNCTION public.cleanup_expired_idempotency_keys() TO service_role;

NOTIFY pgrst, 'reload schema';
